name: Android CI

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Build with Gradle
        run: |
          cd Android
          ./gradlew build 
          
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd Android
          ./gradlew test --info
          
