name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup JDK
        uses: actions/setup-java@v3.1.1
        with:
          java-version: 1.8
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.5
      
          
